POST http://localhost:8080/api/owner
Content-Type: application/json

{
  "firstName": "Attila",
  "lastName": "Papucs"
}

###

PUT http://localhost:8080/api/owner
Content-Type: application/json

{
  "id": 1,
  "firstName": "Attila",
  "lastName": "Papucs"
}

###
GET http://localhost:8080/api/owner
Accept: application/json

###

GET http://localhost:8080/api/owner/data/1
Accept: application/json

###

DELETE http://localhost:8080/api/owner/5
Accept: application/json

###

