POST http://localhost:8080/api/owner
Content-Type: application/json

{
  "firstName": "Papa",
  "lastName": "Papucs"
}

###

PUT http://localhost:8080/api/owner
Content-Type: application/json

{
  "id": 6,
  "firstName": "Attila",
  "lastName": "Papucska"
}

###
GET http://localhost:8080/api/owner
Accept: application/json

###

GET http://localhost:8080/api/owner/data/4
Accept: application/json

###

DELETE http://localhost:8080/api/owner/6
Accept: application/json

###

