POST http://localhost:8080/api/car
Content-Type: application/json

{
  "manufacturer": "Mercedes",
  "type": "Benz",
  "licensePlateNumber": "xyz-987",
  "doorNumbers": 5,
  "ownerID": 1
}

###

PUT http://localhost:8080/api/car
Content-Type: application/json

{
  "id": 1,
  "manufacturer": "Mercedes",
  "type": "M3",
  "licensePlateNumber": "xyz-987",
  "doorNumbers": 2,
  "ownerID": 1
}

###
GET http://localhost:8080/api/car
Accept: application/json

###

DELETE http://localhost:8080/api/car/3
Accept: application/json

###

