POST http://localhost:8080/api/plane
Content-Type: application/json

{
  "manufacturer": "Jet",
  "type": "vadászgép",
  "passengerNumber": 100,
  "ownerID": 1
}

###

PUT http://localhost:8080/api/plane
Content-Type: application/json

{
  "id": 7,
  "manufacturer": "Turbo Jet",
  "type": "vadászgép",
  "passengerNumber": 20,
  "ownerID": 2
}

###
GET http://localhost:8080/api/plane
Accept: application/json

###

GET http://localhost:8080/api/plane/7
Accept: application/json

###

GET http://localhost:8080/api/plane/owner_id/1
Accept: application/json

###

DELETE http://localhost:8080/api/plane/7
Accept: application/json

###

