POST http://localhost:8080/api/ship
Content-Type: application/json

{
  "manufacturer": "Jenny",
  "type": "Joker",
  "licensePlateNumber": "xyz-555",
  "ownerID": 1
}

###

PUT http://localhost:8080/api/ship
Content-Type: application/json

{
  "id": 7,
  "manufacturer": "Jane",
  "type": "Joker",
  "licensePlateNumber": "xyz-666",
  "ownerID": 2
}

###
GET http://localhost:8080/api/ship
Accept: application/json

###

GET http://localhost:8080/api/ship/10
Accept: application/json

###

GET http://localhost:8080/api/ship/owner_id/2
Accept: application/json

###

DELETE http://localhost:8080/api/ship/7
Accept: application/json

###

